title: Debug Pico code
hero_image: images/banner.png
description: Tips voor foutopsporing van MicroPython code voor de Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-03-07"
steps:
  - 
    title: Debug Pico code

