title: Debug Pico code
hero_image: images/banner.png
description: debug-pico-code description
version: 4
listed: false
copyedit: false
last_tested: "2022-03-07"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
